############################## Classhelper Config ##############################
# The settings will not be changed until the server restart
# Do not delete any uncommented line even if it seems useless
# See config.default.yml for the default config
# For more helps, see http://yaml.org/ or google "yaml"
################################################################################

###################### Server Section ######################
# Control the server's network settings
# use in bin/www
############################################################
server:
    # Listen on a port if no socket set
    # Valid: port number
    # Invalid when socket set
    # Default: 3000
    port: 3000
    # Listen address
    # Valid: ip or host
    # Optional, invalid when socket set
    # Default: ~(null) means all addresses
    addr: ~
    # Use unix socket
    # Valid: socket file path
    # Optional
    # Default: ~(null)
    socket: ~
    # Host for outer url
    # Include the scheme (http or https) and port(optinal when use default port)
    # Exclude the last '/'
    # Example: https://classhelper.ml or http://123.123.123.123:3000
    # Default: http://localhost:3000
    host: http://localhost:3000

################### Application Section ####################
# Control the behaviors or secure settings
# use in app.js
############################################################
app:
    # It's recomended to change the secret by yourself
    # Set the store to use persistent session
    # For more detail, see https://github.com/expressjs/session#options
    session:
        secret: _CLASS_HELPER_
        key: sessionid
        resave: true
        saveUninitialized: true
        cookie: { secure: false }
    # Debug mode or not, error page are different
    # Valid: true, false
    # Default: false
    debug: false
    # Access log level
    # Valid: combined, common, dev, short, tiny, ~(null, means no log)
    #        or custom log format like ':method :url :response-time'
    # For more detail, see https://github.com/expressjs/morgan
    # Default: dev
    accesslog: dev
    # Set which kind of error will be logged
    # The value will be used as regular expression
    # Valid: ~(null), .*(all), 40*, 50* ...
    # Default: 50*
    errorlog: 50*

###################### MySQL Section #######################
# Control how this application connect to MySQL server
# use in dao/dao.js
# For more helps, see https://github.com/mysqljs/mysql
############################################################
sql:
    # MySQL server host
    # Valid: ip or host
    # No default values, must be set by yourself
    host:
    # MySQL user name
    user:
    # MySQL password
    password:
    # MySQL database
    database:
    # MySQL charset
    # Default: utf8mb4_unicode_ci
    charset: utf8mb4_unicode_ci

####################### User Section #######################
# Control user register
# Use in controllers/user-manager.js
############################################################
user:
    # Verify user's email or not
    # If true, application will send an email to user,
    #     and the user account will not be valid until confirmed
    # Remember to configure smtp if it's set to true
    # Valid: true, false
    # Default: false
    verifyemail: false
    # Allow user reset password by email
    # Remember to configure smtp if it's set to true
    # Valid: true, false
    # Default: false
    resetpassword: false
    # Which kind of email address will be allowed
    # The value will be used as regular expression
    # Invalid when verifyemail is false
    # Invalid when no any user registered yet
    # Valid: '@'(allow all), ~(allow none)
    #        '@mail.com'(allow this email server)
    #        '@(gmail|live).com'(allow these two kinds)
    # Default: '@'
    allowemail: '@'

####################### SMTP Section #######################
# Email server for sending email
# Use in controllers/user-manager.js
# For more helps, see https://nodemailer.com/about/
############################################################
smtp:
    # Use famous service or host & port
    # Service: famous email service name (no host or port needed)
    # Note: leave service empty to use host and port
    service:
    host:
    port:
    secure: true
    auth:
        user:
        pass:
